import os
from datetime import datetime

from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from fastapi.responses import FileResponse
from bson import ObjectId

from database import invoices_col, bank_statements_col, trades_col, serialize_doc, create_notification
from auth import require_roles
from models import InvoiceCreate, BankStatementCreate

UPLOAD_DIR = "/app/backend/uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

accounting_access = require_roles("admin", "accountant")

router = APIRouter(prefix="/api", tags=["accounting"])


# ─── Invoices ────────────────────────────────────────────────
@router.get("/invoices")
def list_invoices(user=Depends(accounting_access)):
    return [serialize_doc(i) for i in invoices_col.find().sort("createdAt", -1)]


@router.post("/invoices")
def create_invoice(invoice: InvoiceCreate, user=Depends(accounting_access)):
    data = invoice.dict()
    data["createdAt"] = datetime.utcnow()
    result = invoices_col.insert_one(data)
    data["_id"] = result.inserted_id
    create_notification("accounting", f"New invoice: {data.get('invoiceNumber', '')}", str(result.inserted_id), user.get("username"))
    return serialize_doc(data)


@router.put("/invoices/{invoice_id}")
def update_invoice(invoice_id: str, invoice: InvoiceCreate, user=Depends(accounting_access)):
    data = invoice.dict()
    invoices_col.update_one({"_id": ObjectId(invoice_id)}, {"$set": data})
    create_notification("accounting", f"Invoice updated: {data.get('invoiceNumber', '')}", invoice_id, user.get("username"))
    return serialize_doc(invoices_col.find_one({"_id": ObjectId(invoice_id)}))


@router.delete("/invoices/{invoice_id}")
def delete_invoice(invoice_id: str, user=Depends(accounting_access)):
    inv = invoices_col.find_one({"_id": ObjectId(invoice_id)})
    invoices_col.delete_one({"_id": ObjectId(invoice_id)})
    create_notification("accounting", f"Invoice deleted: {inv.get('invoiceNumber', '') if inv else invoice_id}", invoice_id, user.get("username"))
    return {"message": "Deleted"}


@router.patch("/invoices/{invoice_id}/payment-date")
def update_invoice_payment_date(invoice_id: str, body: dict, user=Depends(accounting_access)):
    payment_date = body.get("paymentDate", "")
    inv = invoices_col.find_one({"_id": ObjectId(invoice_id)})
    if not inv:
        return {"error": "Invoice not found"}
    update = {"paymentDate": payment_date}
    if payment_date:
        update["status"] = "paid"
    else:
        update["status"] = "pending"
    invoices_col.update_one({"_id": ObjectId(invoice_id)}, {"$set": update})
    # Sync to trade's buyerPaymentDate
    trade_id = inv.get("tradeId")
    if trade_id and inv.get("autoGenerated"):
        trade_update = {"buyerPaymentDate": payment_date}
        if payment_date:
            trade_update["invoicePaid"] = True
        else:
            trade_update["invoicePaid"] = False
        trades_col.update_one({"_id": ObjectId(trade_id)}, {"$set": trade_update})
    return serialize_doc(invoices_col.find_one({"_id": ObjectId(invoice_id)}))



@router.post("/invoices/{invoice_id}/upload-file")
async def upload_invoice_file(invoice_id: str, file: UploadFile = File(...), user=Depends(accounting_access)):
    inv = invoices_col.find_one({"_id": ObjectId(invoice_id)})
    if not inv:
        raise HTTPException(status_code=404, detail="Invoice not found")
    inv_dir = os.path.join(UPLOAD_DIR, "invoices")
    os.makedirs(inv_dir, exist_ok=True)
    ext = os.path.splitext(file.filename)[1]
    stored_name = f"{invoice_id}{ext}"
    path = os.path.join(inv_dir, stored_name)
    with open(path, "wb") as f:
        f.write(await file.read())
    invoices_col.update_one({"_id": ObjectId(invoice_id)}, {"$set": {"invoiceFileName": file.filename, "invoiceFilePath": path}})
    return serialize_doc(invoices_col.find_one({"_id": ObjectId(invoice_id)}))


@router.get("/invoices/{invoice_id}/download-file")
def download_invoice_file(invoice_id: str, user=Depends(accounting_access)):
    inv = invoices_col.find_one({"_id": ObjectId(invoice_id)})
    if not inv or not inv.get("invoiceFilePath"):
        raise HTTPException(status_code=404, detail="No file found")
    path = inv["invoiceFilePath"]
    if not os.path.exists(path):
        raise HTTPException(status_code=404, detail="File not found on disk")
    return FileResponse(path, filename=inv.get("invoiceFileName", "invoice.pdf"), media_type="application/octet-stream")


@router.delete("/invoices/{invoice_id}/upload-file")
def delete_invoice_file(invoice_id: str, user=Depends(accounting_access)):
    inv = invoices_col.find_one({"_id": ObjectId(invoice_id)})
    if not inv:
        raise HTTPException(status_code=404, detail="Invoice not found")
    path = inv.get("invoiceFilePath")
    if path and os.path.exists(path):
        os.remove(path)
    invoices_col.update_one({"_id": ObjectId(invoice_id)}, {"$unset": {"invoiceFileName": "", "invoiceFilePath": ""}})
    return serialize_doc(invoices_col.find_one({"_id": ObjectId(invoice_id)}))



# ─── Bank Statements ────────────────────────────────────────
@router.get("/bank-statements")
def list_bank_statements(user=Depends(accounting_access)):
    return [serialize_doc(s) for s in bank_statements_col.find().sort("createdAt", -1)]


@router.post("/bank-statements")
def create_bank_statement(stmt: BankStatementCreate, user=Depends(accounting_access)):
    data = stmt.dict()
    data["createdAt"] = datetime.utcnow()
    result = bank_statements_col.insert_one(data)
    data["_id"] = result.inserted_id
    create_notification("accounting", "New bank statement added", str(result.inserted_id), user.get("username"))
    return serialize_doc(data)


@router.post("/bank-statements/upload")
async def upload_bank_statement(
    file: UploadFile = File(...),
    month: int = Form(...),
    year: int = Form(...),
    description: str = Form(""),
    bankAccountId: str = Form(""),
    user=Depends(accounting_access),
):
    allowed = ('.pdf', '.doc', '.docx', '.xls', '.xlsx', '.csv', '.jpg', '.jpeg', '.png')
    if not file.filename.lower().endswith(allowed):
        raise HTTPException(status_code=400, detail="File type not allowed")
    data = {
        "month": month,
        "year": year,
        "description": description,
        "bankAccountId": bankAccountId,
        "fileName": file.filename,
        "createdAt": datetime.utcnow(),
    }
    result = bank_statements_col.insert_one(data)
    stmt_id = str(result.inserted_id)
    ext = file.filename.rsplit('.', 1)[-1] if '.' in file.filename else 'pdf'
    stored_name = f"stmt_{stmt_id}.{ext}"
    filepath = os.path.join(UPLOAD_DIR, stored_name)
    content = await file.read()
    with open(filepath, "wb") as f:
        f.write(content)
    bank_statements_col.update_one({"_id": result.inserted_id}, {"$set": {"storedFileName": stored_name}})
    data["_id"] = result.inserted_id
    data["storedFileName"] = stored_name
    create_notification("accounting", "Bank statement uploaded", stmt_id, user.get("username"))
    return serialize_doc(data)


@router.get("/bank-statements/{stmt_id}/download")
def download_bank_statement(stmt_id: str, user=Depends(accounting_access)):
    stmt = bank_statements_col.find_one({"_id": ObjectId(stmt_id)})
    if not stmt or not stmt.get("storedFileName"):
        raise HTTPException(status_code=404, detail="No file found")
    filepath = os.path.join(UPLOAD_DIR, stmt["storedFileName"])
    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail="File not found on disk")
    return FileResponse(filepath, filename=stmt.get("fileName", "bank_statement"), media_type="application/octet-stream")


@router.delete("/bank-statements/{stmt_id}")
def delete_bank_statement(stmt_id: str, user=Depends(accounting_access)):
    bank_statements_col.delete_one({"_id": ObjectId(stmt_id)})
    create_notification("accounting", "Bank statement deleted", stmt_id, user.get("username"))
    return {"message": "Deleted"}
