VESSELS = [
    {"name": "MV ABDUL", "imoNumber": "9465497", "vesselType": "Bulk Carrier", "flag": "St. Kitts and Nevis", "builtYear": 2007},
    {"name": "MV ANGELA", "imoNumber": "9071076", "vesselType": "Bulk Carrier", "flag": "St. Kitts and Nevis", "builtYear": 1995},
    {"name": "MV VIKING", "imoNumber": "8230429", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1979},
    {"name": "MV ASTRA MERIDIAN", "imoNumber": "8721399", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1986},
    {"name": "MV ASTROL-3", "imoNumber": "9914266", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2021},
    {"name": "MV ATLAS BEY", "imoNumber": "8302404", "vesselType": "Bulk Carrier", "flag": "Tanzania", "builtYear": 1985},
    {"name": "MV AYSSEL", "imoNumber": "9155896", "vesselType": "Bulk Carrier", "flag": "Liberia", "builtYear": 1997},
    {"name": "MV AZ HORIZON", "imoNumber": "9563885", "vesselType": "Bulk Carrier", "flag": "Sierra Leone", "builtYear": 2009},
    {"name": "MV AZOV", "imoNumber": "9156204", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1996},
    {"name": "MV BAHAR", "imoNumber": "8230156", "vesselType": "Bulk Carrier", "flag": "Cameroon", "builtYear": 1971},
    {"name": "MV BARABULKA", "imoNumber": "8887296", "vesselType": "Bulk Carrier", "flag": "Cameroon", "builtYear": 1995},
    {"name": "MV BELLA", "imoNumber": "8418356", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1985},
    {"name": "MV BON", "imoNumber": "8201002", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1985},
    {"name": "MV BRATSK", "imoNumber": "8888070", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV BUNDU", "imoNumber": "9273014", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 2003},
    {"name": "MV CARLOW", "imoNumber": "9127162", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1995},
    {"name": "MV CHELSEA-3", "imoNumber": "9361392", "vesselType": "Bulk Carrier", "flag": "Malta", "builtYear": 2006},
    {"name": "MV CHELSEA-5", "imoNumber": "9386158", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 2007},
    {"name": "MV COMANCHE", "imoNumber": "8955720", "vesselType": "Bulk Carrier", "flag": "Liberia", "builtYear": 1991},
    {"name": "MV CORSAGE C", "imoNumber": "8203684", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1982},
    {"name": "MV DALIA", "imoNumber": "7911595", "vesselType": "Bulk Carrier", "flag": "Saint Kitts & Nevis", "builtYear": 1981},
    {"name": "MV DAY FOREST", "imoNumber": "8857992", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1982},
    {"name": "MV DEDEM", "imoNumber": "9001124", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1993},
    {"name": "MV AYSTAR", "imoNumber": "9257204", "vesselType": "Bulk Carrier", "flag": "Tuvalu", "builtYear": 2001},
    {"name": "MV DIAMOND C", "imoNumber": "8866723", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1979},
    {"name": "MV DILEK", "imoNumber": "9169732", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1997},
    {"name": "MV DOGANBEY", "imoNumber": "9111761", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1996},
    {"name": "MV DONMASTER PRIDE", "imoNumber": "9282091", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2002},
    {"name": "MV DRY VOYAGER 1", "imoNumber": "1081192", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 2025},
    {"name": "MV DUNE 2", "imoNumber": "8728048", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1983},
    {"name": "MV ELISA", "imoNumber": "8602000", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1986},
    {"name": "MV ENES D", "imoNumber": "9100152", "vesselType": "Bulk Carrier", "flag": "St Vincent & Grenadines", "builtYear": 1994},
    {"name": "MV ERLE", "imoNumber": "9506576", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 2011},
    {"name": "MV ESENCE", "imoNumber": "7827342", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1982},
    {"name": "MV FK SILA", "imoNumber": "8130851", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1982},
    {"name": "MV FORTUNA", "imoNumber": "7729966", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1977},
    {"name": "MV FORTUNATE", "imoNumber": "9422342", "vesselType": "Bulk Carrier", "flag": "Liberia", "builtYear": 2007},
    {"name": "MV FORWARD", "imoNumber": "8231007", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1973},
    {"name": "MV GALISA", "imoNumber": "8301838", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1982},
    {"name": "MV GELMOND 3", "imoNumber": "9403499", "vesselType": "Bulk Carrier", "flag": "Saint Kitts & Nevis", "builtYear": 2008},
    {"name": "MV GERMAN", "imoNumber": "8884921", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV HALIVER", "imoNumber": "8133566", "vesselType": "Bulk Carrier", "flag": "Tanzania", "builtYear": 1982},
    {"name": "MV HIGHLAND-A", "imoNumber": "9194452", "vesselType": "Bulk Carrier", "flag": "Barbados", "builtYear": 1999},
    {"name": "MV INDIANA JONES I", "imoNumber": "8806149", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1989},
    {"name": "MV ISLAND STAR", "imoNumber": "7382500", "vesselType": "Bulk Carrier", "flag": "Togo", "builtYear": 1976},
    {"name": "MV KAPITAN AVESHNIKOV", "imoNumber": "8332796", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV KAPITAN VORONKOV", "imoNumber": "8623987", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV LIME", "imoNumber": "8857954", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1971},
    {"name": "MV LUCY J", "imoNumber": "7810208", "vesselType": "Bulk Carrier", "flag": "Honduras", "builtYear": 1979},
    {"name": "MV MARMARA PRINCESS", "imoNumber": "8223074", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1983},
    {"name": "MV MARMARA S", "imoNumber": "8103377", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1982},
    {"name": "MV MARTYN LATSIS", "imoNumber": "8038223", "vesselType": "Bulk Carrier", "flag": "Ukraine", "builtYear": 1982},
    {"name": "MV METIN DADAYLI", "imoNumber": "9382827", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 2007},
    {"name": "MV MUHAMMET GUMUSTAS 5", "imoNumber": "8516287", "vesselType": "Bulk Carrier", "flag": "Türkiye", "builtYear": 1985},
    {"name": "MV DONMASTER SPIRIT", "imoNumber": "9282089", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2002},
    {"name": "MV MY EFEKAN 1", "imoNumber": "9048639", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1993},
    {"name": "MV NATAVAN", "imoNumber": "9459618", "vesselType": "Bulk Carrier", "flag": "Azerbaijan", "builtYear": 2008},
    {"name": "MV NAVIS-1", "imoNumber": "9868730", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2019},
    {"name": "MV NEONILA", "imoNumber": "7907233", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1981},
    {"name": "MV NEVA-LEADER 1", "imoNumber": "9598816", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2012},
    {"name": "MV NEVA-LEADER 2", "imoNumber": "9598828", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2012},
    {"name": "MV NIKOLAY KUZNETSOV", "imoNumber": "8036110", "vesselType": "Bulk Carrier", "flag": "Saint Kitts & Nevis", "builtYear": 1982},
    {"name": "MV NIKOLAY MESHKOV", "imoNumber": "8862507", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1980},
    {"name": "MV NIL DEMIR", "imoNumber": "8003814", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1980},
    {"name": "MV NURDOGAN", "imoNumber": "9001930", "vesselType": "Bulk Carrier", "flag": "St Vincent & Grenadines", "builtYear": 1990},
    {"name": "MV OCTOPUS S", "imoNumber": "7636743", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1978},
    {"name": "MV OKHOTSK", "imoNumber": "8887454", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1978},
    {"name": "MV OLIMPIADA", "imoNumber": "9361976", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2006},
    {"name": "MV OMSKIY 107", "imoNumber": "8866759", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1981},
    {"name": "MV OMSKIY 117", "imoNumber": "8874421", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1983},
    {"name": "MV OMSKIY-134", "imoNumber": "8881711", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1988},
    {"name": "MV OPAL", "imoNumber": "8887507", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1972},
    {"name": "MV ORIENTAL", "imoNumber": "9085077", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1994},
    {"name": "MV PAVEL GRABOVSKIY", "imoNumber": "7830911", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1979},
    {"name": "MV TALEEN", "imoNumber": "9565120", "vesselType": "Bulk Carrier", "flag": "Sierra Leone", "builtYear": 2009},
    {"name": "MV PINDUSHI", "imoNumber": "7646918", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1977},
    {"name": "MV RAMZAY", "imoNumber": "9672260", "vesselType": "Bulk Carrier", "flag": "Belize", "builtYear": 2014},
    {"name": "MV RAPID", "imoNumber": "8919233", "vesselType": "Bulk Carrier", "flag": "Tanzania", "builtYear": 1991},
    {"name": "MV RECEP KURU", "imoNumber": "9040948", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1994},
    {"name": "MV RHONE", "imoNumber": "9057305", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1996},
    {"name": "MV RIVER RAIN", "imoNumber": "8865949", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1990},
    {"name": "MV RIVER STORM", "imoNumber": "8833881", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1990},
    {"name": "MV ROSEWOOD", "imoNumber": "8942931", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1973},
    {"name": "MV RUSICH-5", "imoNumber": "9353046", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2005},
    {"name": "MV SAPPHIRE", "imoNumber": "8871338", "vesselType": "Bulk Carrier", "flag": "Sierra Leone", "builtYear": 1984},
    {"name": "MV SEA PIONEER", "imoNumber": "8208919", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1983},
    {"name": "MV SEA PRINCESS", "imoNumber": "9327188", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 2006},
    {"name": "MV SHELEKHOV", "imoNumber": "8721519", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1988},
    {"name": "MV SLAVYANKA", "imoNumber": "8869969", "vesselType": "Bulk Carrier", "flag": "Malta", "builtYear": 2023},
    {"name": "MV SMART", "imoNumber": "8943428", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1987},
    {"name": "MV SOFIA", "imoNumber": "9340269", "vesselType": "Bulk Carrier", "flag": "Guinea-Bissau", "builtYear": 2004},
    {"name": "MV SORMOVO 3", "imoNumber": "8101422", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1983},
    {"name": "MV SORMOVSKIY-123", "imoNumber": "8725632", "vesselType": "Bulk Carrier", "flag": "Cameroon", "builtYear": 1985},
    {"name": "MV SORMOVSKIY-3053", "imoNumber": "8222381", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV SORMOVSKIY-3054", "imoNumber": "8222393", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV SORMOVSKIY-3056", "imoNumber": "8419623", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1986},
    {"name": "MV SORMOVSKIY-3057", "imoNumber": "8419635", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1987},
    {"name": "MV SORMOVSKIY-3058", "imoNumber": "8419647", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1987},
    {"name": "MV SUM", "imoNumber": "9005467", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1991},
    {"name": "MV SUNDRY", "imoNumber": "9045651", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 2000},
    {"name": "MV SV. GEORGIY POBEDONOSETS", "imoNumber": "9247637", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2003},
    {"name": "MV SYMPATHY", "imoNumber": "8951346", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1972},
    {"name": "MV UNZILE ANA", "imoNumber": "9133367", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1996},
    {"name": "MV VEGA", "imoNumber": "8744224", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1996},
    {"name": "MV VERLAINE", "imoNumber": "8841694", "vesselType": "Bulk Carrier", "flag": "Tanzania", "builtYear": 1980},
    {"name": "MV VIRMA 2", "imoNumber": "8230481", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1981},
    {"name": "MV VODLA 2", "imoNumber": "8230572", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1983},
    {"name": "MV VOLGO-BALT 206", "imoNumber": "8230340", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1977},
    {"name": "MV VOLGO-BALT 213", "imoNumber": "8841632", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1978},
    {"name": "MV VOLGO-BALT 227", "imoNumber": "8841723", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1980},
    {"name": "MV VOLGO-BALT 230", "imoNumber": "8230443", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1981},
    {"name": "MV VOLGO-BALT 237", "imoNumber": "8230510", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1983},
    {"name": "MV VOLGO-BALT 240", "imoNumber": "8230546", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1982},
    {"name": "MV VOLGO-BALT 245", "imoNumber": "8230596", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1983},
    {"name": "MV VOLGO DON 207", "imoNumber": "8959178", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1977},
    {"name": "MV VOLGO-DON 5021", "imoNumber": "8955873", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1970},
    {"name": "MV VOLZHSKIY-44", "imoNumber": "8873489", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1991},
    {"name": "MV VYACHESLAV PAYSHCHIKOV", "imoNumber": "9942407", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2024},
    {"name": "MV YARA", "imoNumber": "9046667", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1992},
    {"name": "MV YAROPOLK", "imoNumber": "8871572", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1987},
    {"name": "MV NEVA-LEADER 7", "imoNumber": "9598878", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2013},
    {"name": "MV OMSKIY 99", "imoNumber": "8943399", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1979},
    {"name": "MV MEDITERRANEAN STAR", "imoNumber": "9876543", "vesselType": "Bulk Carrier", "flag": "Malta", "builtYear": 2015},
    {"name": "MV NAVAHO", "imoNumber": "9220445", "vesselType": "Bulk Carrier", "flag": "Liberia", "builtYear": 1999},
    {"name": "MV VOLGO-BALT 231", "imoNumber": "8230455", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1981},
    {"name": "MV HIMALAYA", "imoNumber": "9231858", "vesselType": "Bulk Carrier", "flag": "Vanuatu", "builtYear": 1999},
    {"name": "MV TAYGA", "imoNumber": "8721466", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1987},
    {"name": "MV OMSKIY-121", "imoNumber": "8871194", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1984},
    {"name": "MV UST-KUT", "imoNumber": "8889397", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1979},
    {"name": "MV NEVA-LEADER 4", "imoNumber": "9598842", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2013},
    {"name": "MV CHEYENNE", "imoNumber": "9142875", "vesselType": "Bulk Carrier", "flag": "Liberia", "builtYear": 1993},
    {"name": "MV RUSICH-11", "imoNumber": "9368259", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2007},
    {"name": "MV PRINCESS EMAN", "imoNumber": "8129321", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1988},
    {"name": "MV CIRCON", "imoNumber": "8887519", "vesselType": "General Cargo Ship", "flag": "Palau", "builtYear": 1972},
    {"name": "MV TULUN", "imoNumber": "8230326", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1977},
    {"name": "MV IVAN BELOV", "imoNumber": "9942419", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2023},
    {"name": "MV NAVIS-2", "imoNumber": "9868742", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2019},
    {"name": "MV NOVOCHERKASSK", "imoNumber": "9083328", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1993},
    {"name": "MV CHELSEA-6", "imoNumber": "9386160", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 2008},
    {"name": "MV SVETOSLAVA", "imoNumber": "8863343", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1971},
    {"name": "MV DIAMOND", "imoNumber": "8935457", "vesselType": "Bulk Carrier", "flag": "Sierra Leone", "builtYear": 1986},
    {"name": "MV TOTOKHON", "imoNumber": "8728062", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1980},
    {"name": "MV ARIYA", "imoNumber": "8858673", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1992},
    {"name": "MV OMSKIY-133", "imoNumber": "8873336", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1988},
    {"name": "MV OMSKIY-137", "imoNumber": "8873087", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1988},
    {"name": "MV ALEKSEY AFANASYEV", "imoNumber": "8033132", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1981},
    {"name": "MV CAPITAN KORCHIN", "imoNumber": "8959219", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1978},
    {"name": "MV VOLGO-DON 211", "imoNumber": "8959180", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1977},
    {"name": "MV VOLGOGRAD", "imoNumber": "8847260", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1991},
    {"name": "MV SORMOVSKIY-3052", "imoNumber": "8222379", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1984},
    {"name": "MV SORMOVSKIY-53", "imoNumber": "8628133", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1986},
    {"name": "MV SORMOVSKIY-3064", "imoNumber": "8702252", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1989},
    {"name": "MV ONERIVA 42", "imoNumber": "8862325", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV MUHAMMET GUMUSTAS 6", "imoNumber": "8509832", "vesselType": "Bulk Carrier", "flag": "Türkiye", "builtYear": 1985},
    {"name": "MV OMSKIY-125", "imoNumber": "8865937", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1985},
    {"name": "MV GLEN", "imoNumber": "9125061", "vesselType": "Bulk Carrier", "flag": "Barbados", "builtYear": 1996},
    {"name": "MV NEW LIFE", "imoNumber": "8876510", "vesselType": "Bulk Carrier", "flag": "Cameroon", "builtYear": 1974},
    {"name": "MV SNP PAZAR", "imoNumber": "9549310", "vesselType": "Bulk Carrier", "flag": "Barbados", "builtYear": 2010},
    {"name": "MV LAZURIT", "imoNumber": "8957132", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1988},
    {"name": "MV SV. APOSTOL ANDREY", "imoNumber": "9247601", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2002},
    {"name": "MV VOLODYMYR VOROBYOV", "imoNumber": "7945857", "vesselType": "Bulk Carrier", "flag": "Saint Kitts & Nevis", "builtYear": 1981},
    {"name": "MV VIKTOR BORISOV", "imoNumber": "7801908", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1980},
    {"name": "MV SAHIN 4", "imoNumber": "8913318", "vesselType": "Bulk Carrier", "flag": "Türkiye", "builtYear": 1993},
    {"name": "MV ULAN-UDE", "imoNumber": "8721478", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1987},
    {"name": "MV BELFAST", "imoNumber": "8035166", "vesselType": "Bulk Carrier", "flag": "Tanzania", "builtYear": 1982},
    {"name": "MV NIKOLAI PSOMIADI", "imoNumber": "8858439", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1986},
    {"name": "MV HASAN G", "imoNumber": "9136852", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1996},
    {"name": "MV AT 27", "imoNumber": "9136539", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 1997},
    {"name": "MV MKK 1", "imoNumber": "8902929", "vesselType": "Bulk Carrier", "flag": "Saint Kitts & Nevis", "builtYear": 1992},
    {"name": "MV SARA RS", "imoNumber": "8594265", "vesselType": "Bulk Carrier", "flag": "Palau", "builtYear": 2004},
    {"name": "TEST VESSEL", "imoNumber": "1234567", "vesselType": "-", "flag": "Test", "builtYear": 2020},
    {"name": "MV PRINCE FAROUK", "imoNumber": "9125229", "vesselType": "Bulk Carrier", "flag": "Sierra Leone", "builtYear": 1997},
    {"name": "MV ENERGY-2", "imoNumber": "1076850", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2024},
    {"name": "MV VIKING", "imoNumber": "8899988", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1987},
    {"name": "MV DONSTAR 4", "imoNumber": "7911478", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1981},
    {"name": "MV ALEXANDRA 1", "imoNumber": "8876340", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1991},
    {"name": "MV VOLGO-BALT 236", "imoNumber": "8230508", "vesselType": "Bulk Carrier", "flag": "Belize", "builtYear": 1982},
    {"name": "MV IMI", "imoNumber": "9063873", "vesselType": "Bulk Carrier", "flag": "Bahamas", "builtYear": 1993},
    {"name": "MV ALTAIR", "imoNumber": "8943416", "vesselType": "Bulk Carrier", "flag": "Sierra Leone", "builtYear": 1988},
    {"name": "MV DON STAR 6", "imoNumber": "8951396", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1987},
    {"name": "MV POM", "imoNumber": "9127980", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1996},
    {"name": "MV M. T. EFREMOV", "imoNumber": "9851139", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2023},
    {"name": "MV ONUR", "imoNumber": "8853594", "vesselType": "Bulk Carrier", "flag": "Saint Kitts & Nevis", "builtYear": 1991},
    {"name": "MV SVYATITEL ALEKSIY", "imoNumber": "9247625", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2003},
    {"name": "MV VOLGO-DON 213", "imoNumber": "8959192", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1977},
    {"name": "MV BURCUM-I", "imoNumber": "9146405", "vesselType": "Bulk Carrier", "flag": "Türkiye", "builtYear": 1997},
    {"name": "MV LEONID BAGROV", "imoNumber": "9963322", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2025},
    {"name": "MV ENERGY-1", "imoNumber": "1076848", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 2024},
    {"name": "MV TALIA", "imoNumber": "8877825", "vesselType": "Bulk Carrier", "flag": "Comoros", "builtYear": 1994},
    {"name": "MV INANDI", "imoNumber": "8332100", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1984},
    {"name": "MV UMIT G", "imoNumber": "9041124", "vesselType": "Bulk Carrier", "flag": "Panama", "builtYear": 1991},
    {"name": "MV SORMOVSKIY-3060", "imoNumber": "8702214", "vesselType": "Bulk Carrier", "flag": "Russia", "builtYear": 1988},
    {"name": "MV GUNEY", "imoNumber": "8230417", "vesselType": "Bulk Carrier", "flag": "Honduras", "builtYear": 1979},
    {"name": "MV LADY NURAY", "imoNumber": "9038373", "vesselType": "Bulk Carrier", "flag": "Belize", "builtYear": 1992},
]
